# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ceiba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ceiba
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SwiftSpinner'

  target 'ceibaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ceibaUITests' do
    # Pods for testing
  end

end
